# Generated by Django 5.2.5 on 2025-08-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBeastSchools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cabinet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyBeastSchools.cabinet'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(default=None, to='MyBeastSchools.subject'),
        ),
    ]
